let tab = [
    {
        tab:"all",
        txt:"全部",
        isIndex:true
    },
    {
        tab:"top",
        txt:"置顶",
        color:"magenta",
        isIndex:false
    },
    {
        tab:"good",
        txt:"精华",
        color:"geekblue",
        isIndex:true
    },
    {
        tab:"ask",
        txt:"问题",
        color:"green",
        isIndex:true
    },
    {
        tab:"share",
        txt:"分享",
        color:"purple",
        isIndex:true
    },
    {
        tab:"job",
        txt:"招聘",
        color:"cyan",
        isIndex:true
    },
    {
        tab:"dev",
        txt:"测试",
        color:"lime",
        isIndex:true
    }
];
export default tab;